# -*- coding: utf-8 -*-
"""data_labeling_for_classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d79YWbdFL_T3p9i0shUGjTyQBlKyA5NK
"""

import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from datetime import timedelta

from google.colab import drive
drive.mount('/content/drive')

preprocessed_file_path = '/content/drive/MyDrive/Colab Notebooks/DATA CUACA HARIAN BMKG (1 JANUARI 2022 - 31 DESEMBER 2024)_preprocessing result.csv'

data = pd.read_csv(preprocessed_file_path, parse_dates=['Tanggal'], index_col='Tanggal')

"""# **Normalisasi dan Transformasi Data**"""

scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data[['RH_avg', 'Tavg', 'RR', 'ss']])

#hasil setelah dinormalisasi
data_scaled = pd.DataFrame(data_scaled, columns=['RH_avg', 'Tavg', 'RR', 'ss'], index=data.index)
print(data_scaled.head())

#dataFrame hasil normalisasi
data_scaled_df = pd.DataFrame(data_scaled, columns=['RH_avg', 'Tavg', 'RR', 'ss'], index=data.index)

data.index = pd.to_datetime(data.index)

start_date = '2024-06-02'
end_date = '2024-06-30'

filtered_data = data[(data.index >= start_date) & (data.index <= end_date)]

print(filtered_data)#cek data uji

"""## **Pemberian Label Klasifikasi**

1. Copeland Score (Mencari bobot masing-masing parameter)

Jika Kelembapan (RH_avg) > Tavg > RR > SS, maka urutannya dalam hal pengaruh terhadap pertumbuhan tanaman jeruk dapat dilihat sebagai berikut:
1. Kelembapan Udara (RH_avg) - Parameter yang paling berpengaruh.
2. Suhu Udara (Tavg) - Parameter kedua setelah kelembapan.
3. Curah Hujan (RR) - Parameter ketiga.
4. Lama Penyinaran Matahari (ss) - Parameter yang paling kurang berpengaruh.
"""

comparisons = {
    'Parameter': ['Kelembapan Udara', 'Kelembapan Udara', 'Kelembapan Udara', 'Suhu Udara', 'Suhu Udara', 'Curah Hujan'],
    'Against': ['Suhu Udara', 'Curah Hujan', 'Penyinaran Matahari', 'Curah Hujan', 'Penyinaran Matahari', 'Penyinaran Matahari'],
    'Winner': ['Kelembapan Udara', 'Kelembapan Udara', 'Kelembapan Udara', 'Suhu Udara', 'Suhu Udara', 'Curah Hujan']
}

comparison_df = pd.DataFrame(comparisons)

parameters = ['Kelembapan Udara', 'Suhu Udara', 'Curah Hujan', 'Penyinaran Matahari']

scores = {param: {'win': 0, 'loss': 0} for param in parameters}

#hitung jumlah kemenangan dan kekalahan
for index, row in comparison_df.iterrows():
    winner = row['Winner']
    loser = row['Against']

    #meningkatkan jumlah kemenangan dan kekalahan
    scores[winner]['win'] += 1
    scores[loser]['loss'] += 1

#menghitung Copeland Score
copeland_scores = {}
for param in parameters:
    win = scores[param]['win']
    loss = scores[param]['loss']
    copeland_scores[param] = win - loss

copeland_scores_df = pd.DataFrame([
{'Parameter': param, 'Win': scores[param]['win'], 'Loss': scores[param]['loss'], 'Copeland Score': copeland_scores[param]}
    for param in parameters
])
print("Copeland Score (S):")
print(copeland_scores_df)

sorted_params = sorted(copeland_scores.items(), key=lambda x: x[1], reverse=True)
bobot_prioritas = {param: 4 - i for i, (param, _) in enumerate(sorted_params)}

total_prioritas = sum(bobot_prioritas.values())
normalized_weights = {param: round(score / total_prioritas, 4) for param, score in bobot_prioritas.items()}

bobot_df = pd.DataFrame([
    {'Parameter': param,
     'Copeland Score': copeland_scores[param],
     'Bobot Prioritas': bobot_prioritas[param],
     'Bobot Akhir (w_i)': normalized_weights[param]}
    for param in parameters
])
print("\nBobot WSM Berdasarkan Revisi Dosen:")
print(bobot_df)

w1 = normalized_weights['Kelembapan Udara']       #RH_avg
w2 = normalized_weights['Suhu Udara']            #Tavg
w3 = normalized_weights['Curah Hujan']           #RR
w4 = normalized_weights['Penyinaran Matahari']   #ss

print("\nBobot Kelembapan Udara (w1):", w1)
print("Bobot Suhu Udara (w2):", w2)
print("Bobot Curah Hujan (w3):", w3)
print("Bobot Penyinaran Matahari (w4):", w4)

"""# **Inisiasi Standar Acuan Perawatan Pohon Jeruk**"""

ideal_ranges = {
    'Tavg': (25, 30),
    'RH_avg': (50, 85),
    'ss': (6, 8),
    'RR': (2.6, 8)
}

"""## **Perhitungan WSM**"""

def parameter_score(value, min_ideal, max_ideal):
    return 1.0 if min_ideal <= value <= max_ideal else 0.0

result_parameterValue = pd.DataFrame(index=data.index)

for param in ['RH_avg', 'Tavg', 'RR', 'ss']:
    min_val, max_val = ideal_ranges[param]
    result_parameterValue[param] = data[param].apply(lambda x: parameter_score(x, min_val, max_val))

# Hitung Skor WSM ===
weights = normalized_weights
data['RH_avg_WSM'] = result_parameterValue['RH_avg'] * weights['Kelembapan Udara'] # Using 'Kelembapan Udara' key instead of 'RH_avg'
data['Tavg_WSM']   = result_parameterValue['Tavg'] * weights['Suhu Udara'] # Using 'Suhu Udara' key instead of 'Tavg'
data['RR_WSM']     = result_parameterValue['RR'] * weights['Curah Hujan'] # Using 'Curah Hujan' key instead of 'RR'
data['ss_WSM']     = result_parameterValue['ss'] * weights['Penyinaran Matahari'] # Using 'Penyinaran Matahari' key instead of 'ss'

data['WSM_Score'] = (
    data['RH_avg_WSM'] +
    data['Tavg_WSM'] +
    data['RR_WSM'] +
    data['ss_WSM']
)

"""**Menghitung Threshold Berdasarkan Rata-rata**"""

data['Peluang Pertumbuhan'] = data['WSM_Score'].apply(lambda score: 'Baik' if score > 0.25 else 'Buruk')

# threshold = data['WSM_Score'].mean()
# data['Peluang Pertumbuhan'] = data['WSM_Score'].apply(lambda score: 'Baik' if score >= threshold else 'Buruk')

# print("Threshold:", threshold)

print(data[['Tavg', 'RH_avg', 'RR', 'ss', 'WSM_Score', 'Peluang Pertumbuhan']].head(20))

data['Peluang Pertumbuhan'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    colors=['pink', 'grey'],
    ylabel='',
    title='Distribusi Kategori Cuaca'
)
plt.axis('equal')
plt.show()

#simpan hasil
output_path = '/content/drive/MyDrive/Colab Notebooks/DATA CUACA HARIAN BMKG (1 JANUARI 2022 - 31 DESEMBER 2024)_labelling data result.csv'
data.to_csv(output_path)

print(f"✅ File berhasil disimpan di:\n{output_path}")