# -*- coding: utf-8 -*-
"""Salinan Klasifikasi RF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zOqY_2rKpMDlFyI01akPQTIdwQ-tqRfP
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_score
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.tree import plot_tree
from sklearn.preprocessing import LabelEncoder

from google.colab import drive
drive.mount('/content/drive')

preprocessed_file_path = '/content/drive/MyDrive/Colab Notebooks/DATA CUACA HARIAN BMKG (1 JANUARI 2022 - 31 DESEMBER 2024)_labelling data result.csv'

data = pd.read_csv(preprocessed_file_path, parse_dates=['Tanggal'], index_col='Tanggal')

"""# **Klasifikasi Random Forest**"""

X = data[['RH_avg', 'Tavg', 'RR', 'ss']]
y = data['Peluang Pertumbuhan']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

rf = RandomForestClassifier(random_state=42)

#hyperparameter Tuning pakai GridSearchCV
param_dist = {
    'n_estimators': [100, 150, 200],
    'max_depth': [5, 10, 20, None],
    'min_samples_split': [2, 4, 6],
    'min_samples_leaf': [1, 2, 3],
    'max_features': ['sqrt', 'log2'],
    'criterion': ['gini', 'entropy']
}

random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=10,  #coba 10 kombinasi acak
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    random_state=42,
    verbose=1
)

random_search.fit(X_train, y_train)
best_model = random_search.best_estimator_

test_dates = X_test.index
test_data_real = data.loc[test_dates, ['Tavg', 'RH_avg', 'RR', 'ss']].copy()
test_data_real['Tanggal'] = test_data_real.index
test_data_real['Data Latih'] = y_test.values

y_pred = best_model.predict(X_test)

test_data_real['Data Uji'] = y_pred

test_data_real = test_data_real.reset_index(drop=True)

test_data_real['Tanggal'] = pd.to_datetime(test_data_real['Tanggal'])
test_data_real = test_data_real.sort_values(by='Tanggal')

test_data_real = test_data_real[['Tanggal', 'Tavg', 'RH_avg', 'RR', 'ss', 'Data Latih', 'Data Uji']]

print("\n=== Hasil data Uji (20% terakhir dari dataset) ===")
print(test_data_real)

print("\n=== Hasil data Uji (20% terakhir dari dataset) ===")
print(test_data_real)

#evaluasi Model
y_pred = best_model.predict(X_test)

print("\n=== Best Parameters ===")
print(random_search.best_params_)

print("\n=== Classification Report ===")
print(classification_report(y_test, y_pred))

print("\n=== Akurasi Model: {:.2f}% ===".format(accuracy_score(y_test, y_pred) * 100))

# confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='YlGnBu',
            xticklabels=['Buruk', 'Baik'],
            yticklabels=['Buruk', 'Baik'])
plt.title('Confusion Matrix - Random Forest (Tuned)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.tight_layout()
plt.show()

# Plot salah satu decision tree dari Random Forest
plt.figure(figsize=(20, 10))
plot_tree(
    best_model.estimators_[0],  # ambil tree ke-0 dari Random Forest
    feature_names=['RH_avg', 'Tavg', 'RR', 'ss'],
    class_names=['Buruk', 'Baik'],
    filled=True,
    rounded=True,
    fontsize=10
)
plt.title('Visualisasi Salah Satu Decision Tree dari Random Forest')
plt.show()

# ====== Tambahkan KETERANGAN ======
ideal_ranges = {
    'Tavg': (25, 30),
    'RH_avg': (50, 85),
    'ss': (6, 8),
    'RR': (2.6, 8)
}

# Fungsi penjelasan hasil klasifikasi berdasarkan parameter cuaca
def generate_keterangan(row):
    penjelasan = []
    hasil = row['Data Uji']  # hasil klasifikasi dari model

    # RH_avg
    rh = row['RH_avg']
    rh_min, rh_max = ideal_ranges['RH_avg']
    if rh_min <= rh <= rh_max:
        if hasil == 'Baik':
            penjelasan.append("Kelembapan baik, karena berada dalam kisaran optimal (50–85%).")
    elif rh < rh_min:
        if hasil == 'Buruk':
            penjelasan.append("Kelembapan buruk, karena terlalu rendah dari batas ideal.")
    else:
        if hasil == 'Buruk':
            penjelasan.append("Kelembapan buruk, karena melebihi batas ideal dan dapat mengganggu pertumbuhan.")

    # Tavg
    tavg = row['Tavg']
    tavg_min, tavg_max = ideal_ranges['Tavg']
    if tavg_min <= tavg <= tavg_max:
        if hasil == 'Baik':
            penjelasan.append("Suhu baik, karena berada dalam kisaran optimal (25–30°C).")
    elif tavg < tavg_min:
        if hasil == 'Buruk':
            penjelasan.append("Suhu buruk, karena terlalu rendah dari kisaran optimal.")
    else:
        if hasil == 'Buruk':
            penjelasan.append("Suhu buruk, karena terlalu tinggi dari kisaran optimal.")

    # RR
    rr = row['RR']
    rr_min, rr_max = ideal_ranges['RR']
    if rr_min <= rr <= rr_max:
        if hasil == 'Baik':
            penjelasan.append("Curah hujan baik, karena memadai dalam batas ideal (2,6–8 mm).")
    elif rr < rr_min:
        if hasil == 'Buruk':
            penjelasan.append("Curah hujan buruk, karena terlalu rendah dan berisiko kekeringan.")
    else:
        if hasil == 'Buruk':
            penjelasan.append("Curah hujan buruk, karena terlalu tinggi dan bisa menyebabkan kelebihan air.")

    # SS
    ss = row['ss']
    ss_min, ss_max = ideal_ranges['ss']
    if ss_min <= ss <= ss_max:
        if hasil == 'Baik':
            penjelasan.append("Penyinaran baik, karena cukup lama dan mendukung fotosintesis (6–8 jam).")
    elif ss < ss_min:
        if hasil == 'Buruk':
            penjelasan.append("Penyinaran buruk, karena terlalu singkat untuk fotosintesis optimal.")
    else:
        if hasil == 'Buruk':
            penjelasan.append("Penyinaran buruk, karena terlalu lama dan bisa menyebabkan stres cahaya.")

    return ' '.join(penjelasan)

#urutkan data berdasarkan tanggal
test_data_real = test_data_real.sort_values(by='Tanggal')
test_data_real = test_data_real.reset_index(drop=True)

#tambahkan kolom keterangan
test_data_real['Keterangan'] = test_data_real.apply(generate_keterangan, axis=1)

#menampilkan hasil dengan keterangan
from IPython.display import display, HTML
pd.set_option('display.max_colwidth', None)
pd.set_option('display.expand_frame_repr', False)

print("\n=== Hasil Uji + Keterangan ===")
display(HTML(test_data_real[['Tanggal', 'Tavg', 'RH_avg', 'RR', 'ss', 'Data Latih', 'Data Uji', 'Keterangan']].head(20).to_html(index=False)))

import joblib
from google.colab import files
import os

# Buat direktori 'model' jika belum ada
os.makedirs("model", exist_ok=True)

# Simpan model klasifikasi Random Forest
joblib.dump(best_model, "model/Klasifikasi RF.pkl")

print("✅ Model Random Forest disimpan.")

# Unduh otomatis ke komputer
files.download("model/Klasifikasi RF.pkl")

le = LabelEncoder()
y_encoded = le.fit_transform(y)

k = 5
skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)

train_acc_list = []
test_acc_list = []

print("\n=== Evaluasi per Fold ===")
for fold, (train_idx, test_idx) in enumerate(skf.split(X, y_encoded), 1):  # Mulai dari fold ke-1
    X_train_fold, X_test_fold = X.iloc[train_idx], X.iloc[test_idx]
    y_train_fold, y_test_fold = y_encoded[train_idx], y_encoded[test_idx]

    model = RandomForestClassifier(**random_search.best_params_, random_state=42)
    model.fit(X_train_fold, y_train_fold)

    y_train_pred = model.predict(X_train_fold)
    y_test_pred = model.predict(X_test_fold)

    train_acc = accuracy_score(y_train_fold, y_train_pred)
    test_acc = accuracy_score(y_test_fold, y_test_pred)

    train_acc_list.append(train_acc)
    test_acc_list.append(test_acc)

    print(f"Fold {fold} - Train Accuracy: {train_acc*100:.2f}%, Test Accuracy: {test_acc*100:.2f}%")

# Output akhir rata-rata dari 5 Fold
print("\n=== Rata-rata Akurasi 5-Fold Cross Validation ===")
print(f"Training Accuracy : {np.mean(train_acc_list) * 100:.2f}%")
print(f"Testing Accuracy  : {np.mean(test_acc_list) * 100:.2f}%")

plt.figure(figsize=(6, 4))
ax = sns.countplot(x='Data Uji', data=test_data_real, palette='Set2')
plt.title("Distribusi Kategori Hasil Prediksi (Data Uji)")
plt.xlabel("Kategori Pertumbuhan")
plt.ylabel("Jumlah")

for p in ax.patches:
    ax.annotate(
        format(p.get_height(), '.0f'),
        (p.get_x() + p.get_width() / 2., p.get_height()),
        ha='center', va='center',
        xytext=(0, 10),
        textcoords='offset points'
    )

plt.tight_layout()
plt.show()

"""Berdasarkan grafik distribusi hasil prediksi, model Random Forest memprediksi 91 data sebagai "Baik" dan 129 data sebagai "Buruk". Distribusi ini mendekati sebaran aktual pada data latih, yang menunjukkan bahwa model tidak mengalami bias prediksi terhadap salah satu kategori.

# **Pengujian data baru**
"""

data_baru = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MODEL DENGAN AUGMENTASI DATA/data cuaca januari 2025_contoh data pengujian baru_result labelling.csv')

fitur = ['RH_avg', 'Tavg', 'RR', 'ss']
label = 'Peluang Pertumbuhan'

#prediksi menggunakan model yang sudah dilatih
prediksi_baru = best_model.predict(data_baru[fitur])

#tambahkan hasil prediksi ke data
data_baru['Prediksi RF'] = prediksi_baru

print("\n=== Evaluasi Model Random Forest terhadap Data Baru ===")
print(classification_report(data_baru[label], data_baru['Prediksi RF']))
print("Akurasi:", accuracy_score(data_baru[label], data_baru['Prediksi RF']))

"""*   Data uji berasal dari Januari 2025, yang tidak digunakan saat training model
*   Metode pelabelan masih menggunakan pendekatan WSM yang sama, sehingga kemungkinan pola klasifikasi masih sangat mirip dengan data latih.
*   Model klasifikasi Random Forest berhasil memprediksi dengan akurasi 100% terhadap data Januari 2025 yang belum pernah dilatih sebelumnya.


"""