# -*- coding: utf-8 -*-
"""klasifikasi_random forest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbrOJ-WEvk0V2Q8ZJAoaDlVnOHLaxkRS
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_score
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.tree import plot_tree
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score

from google.colab import drive
drive.mount('/content/drive')

preprocessed_file_path = '/content/drive/MyDrive/Colab Notebooks/DATA CUACA HARIAN BMKG (1 JANUARI 2022 - 31 DESEMBER 2024)_labelling data result.csv'

data = pd.read_csv(preprocessed_file_path, parse_dates=['Tanggal'], index_col='Tanggal')

"""# **Klasifikasi Random Forest**"""

X = data[['RH_avg', 'Tavg', 'RR', 'ss']]
y = data['Peluang Pertumbuhan']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = RandomForestClassifier(
    n_estimators=50,
    max_depth=5,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features='sqrt',
    random_state=42
)

model.fit(X_train, y_train)

test_dates = X_test.index
test_data_real = data.loc[test_dates, ['Tavg', 'RH_avg', 'RR', 'ss']].copy()
test_data_real['Tanggal'] = test_data_real.index
test_data_real['Data Latih'] = y_test.values

y_pred = model.predict(X_test)

test_data_real['Data Uji'] = y_pred

test_data_real = test_data_real.reset_index(drop=True)

test_data_real['Tanggal'] = pd.to_datetime(test_data_real['Tanggal'])
test_data_real = test_data_real.sort_values(by='Tanggal')

test_data_real = test_data_real[['Tanggal', 'Tavg', 'RH_avg', 'RR', 'ss', 'Data Latih', 'Data Uji']]

print("\n=== Hasil data Uji (20% terakhir dari dataset) ===")
print(test_data_real)

y_pred = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_pred, labels=['Baik', 'Buruk'])

plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='YlGnBu',
            xticklabels=['Baik', 'Buruk'],
            yticklabels=['Baik', 'Buruk'])

plt.title('Confusion Matrix - Random Forest (Tuned)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.tight_layout()
plt.show()

y_pred = model.predict(X_test)
cm = confusion_matrix(y_test, y_pred, labels=['Baik', 'Buruk'])

# Ambil nilai TP, FN, FP, TN
TP = cm[0, 0]  # Baik → Baik
FN = cm[0, 1]  # Baik → Buruk
FP = cm[1, 0]  # Buruk → Baik
TN = cm[1, 1]  # Buruk → Buruk

# Hitung metrik evaluasi secara manual
acc_manual = (TP + TN) / (TP + TN + FP + FN)
prec_manual = TP / (TP + FP)
rec_manual = TP / (TP + FN)
f1_manual = 2 * prec_manual * rec_manual / (prec_manual + rec_manual)

# Buat tabel hasil evaluasi
manual_eval = pd.DataFrame({
    'Accuracy (%)': [round(acc_manual * 100, 2)],
    'Precision (%)': [round(prec_manual * 100, 2)],
    'Recall (%)': [round(rec_manual * 100, 2)],
    'F1-Score (%)': [round(f1_manual * 100, 2)]
})

print("\n=== Metrik Evaluasi ===")
print(manual_eval.to_string(index=False))

import matplotlib.pyplot as plt

# Buat DataFrame jika belum
counts_actual = y_test.value_counts().sort_index()
counts_pred = pd.Series(y_pred, index=y_test.index).value_counts().sort_index()

df_plot = pd.DataFrame({
    'Aktual': counts_actual,
    'Prediksi': counts_pred
})

df_plot.plot(kind='bar', figsize=(8, 5), color=['skyblue', 'salmon'])
plt.title('Perbandingan Jumlah Kelas: Aktual vs Prediksi')
plt.ylabel('Jumlah')
plt.xticks(rotation=0)
plt.grid(axis='y')
plt.tight_layout()
plt.show()

# Plot salah satu decision tree dari Random Forest
plt.figure(figsize=(20, 10))
plot_tree(
    model.estimators_[0],  # ambil tree ke-0 dari Random Forest
    feature_names=['RH_avg', 'Tavg', 'RR', 'ss'],
    class_names=['Buruk', 'Baik'],
    filled=True,
    rounded=True,
    fontsize=10
)
plt.title('Visualisasi Salah Satu Decision Tree dari Random Forest')
plt.show()

# Buat DataFrame untuk memudahkan visualisasi
feature_importance = pd.DataFrame({
    'Fitur': X.columns,
    'Importance': model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print(feature_importance)


plt.figure(figsize=(8, 5))
plt.barh(feature_importance['Fitur'], feature_importance['Importance'])
plt.xlabel('Tingkat Pengaruh (Importance)')
plt.title('Feature Importance - Random Forest')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

# import joblib
# from google.colab import files
# import os

# # Buat direktori 'model' jika belum ada
# os.makedirs("model", exist_ok=True)

# # Simpan model klasifikasi Random Forest
# joblib.dump(model, "model/rf_model.pkl")

# print("✅ Model Random Forest disimpan.")

# # Unduh otomatis ke komputer
# files.download("model/rf_model.pkl")

"""# **Pengujian data baru**"""

data_baru = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MODEL DENGAN AUGMENTASI DATA/data cuaca januari 2025_contoh data pengujian baru_result labelling.csv')

fitur = ['RH_avg', 'Tavg', 'RR', 'ss']
label = 'Peluang Pertumbuhan'

#prediksi menggunakan model yang sudah dilatih
prediksi_baru = model.predict(data_baru[fitur])

#tambahkan hasil prediksi ke data
data_baru['Prediksi RF'] = prediksi_baru

print("\n=== Evaluasi Model Random Forest terhadap Data Baru ===")
print(classification_report(data_baru[label], data_baru['Prediksi RF']))
print("Akurasi:", accuracy_score(data_baru[label], data_baru['Prediksi RF']))

"""# **K-Fold Cross Validation Script**"""

best_params = {
    'n_estimators': 50,
    'max_depth': None,
    'min_samples_split': 2,
    'min_samples_leaf': 1,
    'max_features': 'sqrt',
    'random_state': 42
}

model = RandomForestClassifier(**best_params)

# === K-Fold Stratified (5 Fold) ===
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

# === Simpan hasil per fold ===
results = []

print("=== Hasil Evaluasi per Fold (Stratified 5-Fold CV) ===")
for i, (train_index, test_index) in enumerate(skf.split(X, y), 1):
    X_train_fold, X_test_fold = X.iloc[train_index], X.iloc[test_index]
    y_train_fold, y_test_fold = y.iloc[train_index], y.iloc[test_index]

    model.fit(X_train_fold, y_train_fold)
    y_pred = model.predict(X_test_fold)

    acc = accuracy_score(y_test_fold, y_pred)
    prec = precision_score(y_test_fold, y_pred, average='weighted')
    rec = recall_score(y_test_fold, y_pred, average='weighted')
    f1_cv = f1_score(y_test_fold, y_pred, average='weighted')

    results.append([acc, prec, rec, f1])
    print(f"Fold {i}: Accuracy = {acc:.4f}, Precision = {prec:.4f}, Recall = {rec:.4f}, F1 = {f1:.4f}")

# === Rata-rata hasil CV ===
results = np.array(results)
print("\n=== Rata-Rata Hasil CV ===")
print(f"Accuracy : {np.mean(results[:, 0]) * 100:.2f}%")
print(f"Precision: {np.mean(results[:, 1]) * 100:.2f}%")
print(f"Recall   : {np.mean(results[:, 2]) * 100:.2f}%")
print(f"F1 Score : {np.mean(results[:, 3]) * 100:.2f}%")

plt.figure(figsize=(12, 4))
plt.plot(test_data_real['Tanggal'], test_data_real['Data Latih'], label='Aktual', linestyle='--')
plt.plot(test_data_real['Tanggal'], test_data_real['Data Uji'], label='Prediksi', alpha=0.7)
plt.xticks(rotation=45)
plt.title('Grafik Perbandingan Prediksi vs Aktual (Klasifikasi)')
plt.ylabel('Kelas')
plt.legend()
plt.tight_layout()
plt.show()