# -*- coding: utf-8 -*-
"""prediksi_rh_avg_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11fksM7mBdD8WicdoFIRwUN9Tk34fQXUY
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error, mean_absolute_error
from sklearn.model_selection import KFold

from google.colab import drive
drive.mount('/content/drive')

preprocessed_file_path = '/content/drive/MyDrive/Colab Notebooks/DATA CUACA HARIAN BMKG (1 JANUARI 2022 - 31 DESEMBER 2024)_preprocessing result.csv'

data = pd.read_csv(preprocessed_file_path, parse_dates=['Tanggal'], index_col='Tanggal')

# Cek statistik dasar kelembaban udara
print("RH_avg min     :", data['RH_avg'].min())
print("RH_avg max     :", data['RH_avg'].max())
print("RH_avg median  :", data['RH_avg'].median())
print("RH_avg mean    :", data['RH_avg'].mean())
print("RH_avg std dev :", data['RH_avg'].std())
print("RH_avg non-zero count:", (data['RH_avg'] > 0).sum())

"""# **Normalisasi**"""

plt.figure(figsize=(8, 5))
plt.hist(data['RH_avg'], bins=50)
plt.title("Distribusi Curah Hujan (RH_avg) Sebelum MinMaxScaler")
plt.xlabel("RH_avg (setelah scaling)")
plt.ylabel("Frekuensi")
plt.grid(True)
plt.tight_layout()
plt.show()

#ambil data RH_avg asli
rh_asli = data[['RH_avg']].copy()

#menerapkan Moving Average 7 hari
rh_smooth = rh_asli.rolling(window=7, center=True, min_periods=1).mean()
print(rh_smooth[-30:].values)

scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(rh_smooth[['RH_avg']])
scaled_data = pd.DataFrame(data_scaled, columns=['rh_smooth'], index=data.index)

plt.figure(figsize=(8, 5))
plt.hist(data_scaled, bins=50)
plt.title("Distribusi Curah Hujan (RH_avg) Setelah MinMax Scaler")
plt.xlabel("Rh_avg (setelah scaling)")
plt.ylabel("Frekuensi")
plt.grid(True)
plt.tight_layout()
plt.show()

"""# **Model LSTM for RH_Avg**"""

# Membuat dataset untuk LSTM
def create_lstm_dataset(df, time_step=30):
    X, y = [], []
    for i in range(len(df) - time_step):
        X.append(df[i:(i + time_step), 0])
        y.append(df[i + time_step, 0])
    return np.array(X), np.array(y)

# Parameter sesuai tabel
time_step = 30
X, y = create_lstm_dataset(data_scaled, time_step)
X = X.reshape((X.shape[0], X.shape[1], 1))

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# Membangun model LSTM
def build_final_model():
    model = Sequential()
    model.add(LSTM(50, return_sequences=True, input_shape=(X.shape[1], X.shape[2])))  # layer pertama
    model.add(LSTM(50))  # layer kedua
    model.add(Dense(1))  # output layer
    model.compile(optimizer=Adam(learning_rate=0.01), loss='mean_squared_error')
    return model

# Latih model
model = build_final_model()
history = model.fit(X_train, y_train, validation_data=(X_test, y_test),
                    epochs=50, batch_size=72, verbose=1)

# === Evaluasi Model ===
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

y_train_rescaled = scaler.inverse_transform(y_train.reshape(-1, 1))
y_test_rescaled = scaler.inverse_transform(y_test.reshape(-1, 1))
y_train_pred_rescaled = scaler.inverse_transform(y_train_pred)
y_test_pred_rescaled = scaler.inverse_transform(y_test_pred)

train_mape = mean_absolute_percentage_error(y_train_rescaled, y_train_pred_rescaled)
train_rmse = np.sqrt(mean_squared_error(y_train_rescaled, y_train_pred_rescaled))

test_mape = mean_absolute_percentage_error(y_test_rescaled, y_test_pred_rescaled)
test_rmse = np.sqrt(mean_squared_error(y_test_rescaled, y_test_pred_rescaled))

std_test_rh = np.std(y_test_rescaled)

print("=== Evaluasi Model LSTM (Train-Test Split 80:20) ===")
print()
print(f"Training MAPE : {train_mape * 100:.2f}%")
print(f"Testing MAPE  : {test_mape * 100:.2f}%")

print()
# Evaluasi RMSE
print(f"Training RMSE         : {train_rmse:.2f}")
print(f"Testing RMSE          : {test_rmse:.2f}")
print(f"Std Dev RR (Test Set) : {std_test_rh:.2f}")
print(f"RMSE < Std Dev?       : {'✅ Baik' if test_rmse < std_test_rh else '❌ Kurang Baik'}")
print()

#menyusun DataFrame untuk data aktual dan prediksi
result_df = pd.DataFrame({
    'Tanggal': data.index[-len(y_test_rescaled):],
    'Data Aktual RH_Avg': y_test_rescaled.flatten(),
    'Prediksi RH_Avg': y_test_pred_rescaled.flatten()
})

print("Tabel Perbandingan Prediksi dan Data Aktual RH_Avg:")
print(result_df.head(50))

# === Grafik Perbandingan Prediksi dan Aktual (Training) ===
plt.figure(figsize=(12, 5))
plt.plot(y_train_rescaled, label='Aktual Training', color='blue')
plt.plot(y_train_pred_rescaled, label='Prediksi Training', color='orange')
plt.title('Perbandingan Data Aktual dan Prediksi (Training)')
plt.xlabel('Index')
plt.ylabel('RH_Avg')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# === Grafik Perbandingan Prediksi dan Aktual (Testing) ===
plt.figure(figsize=(12, 5))
plt.plot(y_test_rescaled, label='Aktual Testing', color='blue')
plt.plot(y_test_pred_rescaled, label='Prediksi Testing', color='red')
plt.title('Perbandingan Data Aktual dan Prediksi (Testing)')
plt.xlabel('Index')
plt.ylabel('RH_Avg')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# === Prediksi 7 Hari ke Depan ===
print("\n=== Prediksi RH_avg untuk 7 Hari ke Depan ===")
last_30_days = data_scaled[-30:]
input_seq = last_30_days.reshape(1, 30, 1)
future_predictions = []

for _ in range(7):
    next_pred = model.predict(input_seq)[0][0]
    future_predictions.append(next_pred)
    input_seq = np.append(input_seq[:, 1:, :], [[[next_pred]]], axis=1)

pred_7hari_rescaled = scaler.inverse_transform(np.array(future_predictions).reshape(-1, 1))
last_date = data.index[-1]
future_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=7)
pred_7hari_df = pd.DataFrame({
    'Tanggal': future_dates,
    'Prediksi RH_avg': pred_7hari_rescaled.flatten()
})

print(pred_7hari_df)

# Visualisasi Hasil Prediksi 7 Hari ke Depan
plt.figure(figsize=(10, 5))
plt.plot(pred_7hari_df['Tanggal'], pred_7hari_df['Prediksi RH_avg'], marker='o', color='green')
plt.title('Prediksi RH_Avg untuk 7 Hari ke Depan')
plt.xlabel('Tanggal')
plt.ylabel('RH_avg')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# import joblib
# from google.colab import files
# import os

# os.makedirs("model", exist_ok=True)

# # Simpan model dan scaler
# model.save("model/rh_avg_model.h5")
# joblib.dump(scaler, "model/scaler_rh_avg.pkl")

# print("✅ Model & Scaler disimpan.")

# # Unduh otomatis ke perangkat
# files.download("model/rh_avg_model.h5")
# files.download("model/scaler_rh_avg.pkl")