# -*- coding: utf-8 -*-
"""prediksi_ss

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQGC03M9VEVdKY9GLc4dEPz1lS3xITNp
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import KFold

from google.colab import drive
drive.mount('/content/drive')

preprocessed_file_path = '/content/drive/MyDrive/Colab Notebooks/DATA CUACA HARIAN BMKG (1 JANUARI 2022 - 31 DESEMBER 2024)_preprocessing result.csv'

data = pd.read_csv(preprocessed_file_path, parse_dates=['Tanggal'], index_col='Tanggal')

# Cek statistik dasar lama penyinaran matahari
print("SS min     :", data['ss'].min())
print("SS max     :", data['ss'].max())
print("SS median  :", data['ss'].median())
print("SS mean    :", data['ss'].mean())
print("SS std dev :", data['ss'].std())
print("SS non-zero count:", (data['ss'] > 0).sum())

"""# **Normalisasi**"""

plt.figure(figsize=(8, 5))
plt.hist(data['ss'], bins=50)
plt.title("Distribusi Curah Hujan (SS) Sebelum RobustScaler")
plt.xlabel("SS (setelah scaling)")
plt.ylabel("Frekuensi")
plt.grid(True)
plt.tight_layout()
plt.show()

#ambil data SS asli
ss_asli = data[['ss']].copy()

#menerapkan Moving Average 7 hari
ss_smooth = ss_asli.rolling(window=7, center=True, min_periods=1).mean()

scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(ss_smooth[['ss']])
scaled_data = pd.DataFrame(data_scaled, columns=['ss_smooth'], index=data.index)

plt.figure(figsize=(8, 5))
plt.hist(data_scaled, bins=50)
plt.title("Distribusi Curah Hujan (SS) Setelah RobustScaler")
plt.xlabel("SS (setelah scaling)")
plt.ylabel("Frekuensi")
plt.grid(True)
plt.tight_layout()
plt.show()

"""# **Model LSTM for SS**"""

def create_lstm_dataset(df, time_step=30):
    X, y = [], []
    for i in range(len(df) - time_step):
        X.append(df[i:(i + time_step), 0])
        y.append(df[i + time_step, 0])
    return np.array(X), np.array(y)

time_step = 30
X, y = create_lstm_dataset(data_scaled, time_step)
X = X.reshape((X.shape[0], X.shape[1], 1))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

def build_final_model():
    model = Sequential()
    model.add(LSTM(units=96, return_sequences=True, input_shape=(X_train.shape[1], 1)))
    model.add(Dropout(0.3))
    model.add(LSTM(units=64))
    model.add(Dropout(0.1))
    model.add(Dense(1))

    model.compile(optimizer=Adam(learning_rate=0.000779), loss='mean_squared_error')
    return model

model = build_final_model()
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, batch_size=32 )

# === Evaluasi Model ===
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

y_train_rescaled = scaler.inverse_transform(y_train.reshape(-1, 1))
y_test_rescaled = scaler.inverse_transform(y_test.reshape(-1, 1))
y_train_pred_rescaled = scaler.inverse_transform(y_train_pred)
y_test_pred_rescaled = scaler.inverse_transform(y_test_pred)

train_mape = mean_absolute_percentage_error(y_train_rescaled, y_train_pred_rescaled)
train_rmse = np.sqrt(mean_squared_error(y_train_rescaled, y_train_pred_rescaled))
train_mae  = mean_absolute_error(y_train_rescaled, y_train_pred_rescaled)

test_mape = mean_absolute_percentage_error(y_test_rescaled, y_test_pred_rescaled)
test_rmse = np.sqrt(mean_squared_error(y_test_rescaled, y_test_pred_rescaled))
test_mae   = mean_absolute_error(y_test_rescaled,  y_test_pred_rescaled)

std_test_ss = np.std(y_test_rescaled)

print("=== Evaluasi Model LSTM (Train-Test Split 80:20) ===")
print()
print("MAPE tidak digunakan karena SS mengandung nilai 0")
# print(f"Training MAPE : {train_mape * 100:.2f}%")
# print(f"Testing MAPE  : {test_mape * 100:.2f}%")

print()
# Evaluasi RMSE
print(f"Training RMSE         : {train_rmse:.2f}")
print(f"Testing RMSE          : {test_rmse:.2f}")
print(f"Std Dev RR (Test Set) : {std_test_ss:.2f}")
print(f"RMSE < Std Dev?       : {'✅ Baik' if test_rmse < std_test_ss else '❌ Kurang Baik'}")
print()

# Evaluasi MAE
print(f"Training MAE          : {train_mae:.2f}")
print(f"Testing  MAE          : {test_mae:.2f}")

#menyusun DataFrame untuk data aktual dan prediksi
result_df = pd.DataFrame({
    'Tanggal': data.index[-len(y_test_rescaled):],
    'Data Aktual SS': y_test_rescaled.flatten(),
    'Prediksi SS': y_test_pred_rescaled.flatten()
})

print("Tabel Perbandingan Prediksi dan Data Aktual SS:")
print(result_df.head(50))

# === Grafik Perbandingan Prediksi dan Aktual (Training) ===
plt.figure(figsize=(12, 5))
plt.plot(y_train_rescaled, label='Aktual Training', color='blue')
plt.plot(y_train_pred_rescaled, label='Prediksi Training', color='orange')
plt.title('Perbandingan Data Aktual dan Prediksi (Training)')
plt.xlabel('Index')
plt.ylabel('SS')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# === Grafik Perbandingan Prediksi dan Aktual (Testing) ===
plt.figure(figsize=(12, 5))
plt.plot(y_test_rescaled, label='Aktual Testing', color='blue')
plt.plot(y_test_pred_rescaled, label='Prediksi Testing', color='red')
plt.title('Perbandingan Data Aktual dan Prediksi (Testing)')
plt.xlabel('Index')
plt.ylabel('SS')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# === Prediksi 7 Hari ke Depan ===
print("\n=== Prediksi SS untuk 7 Hari ke Depan ===")
last_30_days = data_scaled[-30:]
input_seq = last_30_days.reshape(1, 30, 1)
future_predictions = []

for _ in range(7):
    next_pred = model.predict(input_seq)[0][0]
    future_predictions.append(next_pred)
    input_seq = np.append(input_seq[:, 1:, :], [[[next_pred]]], axis=1)

pred_7hari_rescaled = scaler.inverse_transform(np.array(future_predictions).reshape(-1, 1))
last_date = data.index[-1]
future_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=7)
pred_7hari_df = pd.DataFrame({
    'Tanggal': future_dates,
    'Prediksi SS': pred_7hari_rescaled.flatten()
})

print(pred_7hari_df)

# Visualisasi Hasil Prediksi 7 Hari ke Depan
plt.figure(figsize=(10, 5))
plt.plot(pred_7hari_df['Tanggal'], pred_7hari_df['Prediksi SS'], marker='o', color='green')
plt.title('Prediksi SS untuk 7 Hari ke Depan')
plt.xlabel('Tanggal')
plt.ylabel('SS')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import joblib
from google.colab import files
import os

os.makedirs("model", exist_ok=True)

# Simpan model dan scaler
model.save("model/ss_model.h5")
joblib.dump(scaler, "model/scaler_ss.pkl")

print("✅ Model & Scaler disimpan.")

# Unduh otomatis ke perangkat
files.download("model/ss_model.h5")
files.download("model/scaler_ss.pkl")