# -*- coding: utf-8 -*-
"""Salinan Prediksi RR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1128GOuljlDevTiUoVpohT3KTBeRNc0x5
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import KFold

from google.colab import drive
drive.mount('/content/drive')

preprocessed_file_path = '/content/drive/MyDrive/Colab Notebooks/DATA CUACA HARIAN BMKG (1 JANUARI 2022 - 31 DESEMBER 2024)_preprocessing result.csv'

data = pd.read_csv(preprocessed_file_path, parse_dates=['Tanggal'], index_col='Tanggal')

"""# **Normalisasi**


"""

# Cek statistik dasar curah hujan
print("RR min     :", data['RR'].min())
print("RR max     :", data['RR'].max())
print("RR median  :", data['RR'].median())
print("RR mean    :", data['RR'].mean())
print("RR non-zero count:", (data['RR'] > 0).sum())

plt.figure(figsize=(8, 5))
plt.hist(data['RR'], bins=50)
plt.title("Distribusi Curah Hujan (RR) Sebelum RobustScaler")
plt.xlabel("RR (setelah scaling)")
plt.ylabel("Frekuensi")
plt.grid(True)
plt.tight_layout()
plt.show()

"""❗ Sangat skewed (miring)

❗ Mengandung nilai nol yang dominan

❗ Ada nilai ekstrim/jomplang yang jauh di luar kebanyakan data (outlier)
"""

# # Normalisasi dan Transformasi Data
# scaler = MinMaxScaler()
# data_scaled = scaler.fit_transform(data[['RR']])

# scaled_data = pd.DataFrame(data_scaled, columns=['RR'], index=data.index)

scaler = RobustScaler()
data_scaled = scaler.fit_transform(data[['RR']])
scaled_data = pd.DataFrame(data_scaled, columns=['RR'], index=data.index)

plt.figure(figsize=(8, 5))
plt.hist(data_scaled, bins=50)
plt.title("Distribusi Curah Hujan (RR) Setelah RobustScaler")
plt.xlabel("RR (setelah scaling)")
plt.ylabel("Frekuensi")
plt.grid(True)
plt.tight_layout()
plt.show()

"""setelah normalisasi dengan robustscaler, skala menjadi 0-20 (relatif thd median) dan tdk ada outlier"""

# === Augmentasi Gaussian Noise untuk fitur RR ===

def add_gaussian_noise(data, mean=0.0, std=0.02):
    noise = np.random.normal(loc=mean, scale=std, size=data.shape)
    return np.clip(data + noise, 0, 1)

#buat data augmented
augmented_data = add_gaussian_noise(data_scaled)

#menggabungkan data asli + augment
data_augmented = np.vstack([data_scaled, augmented_data])
data_augmented = pd.DataFrame(data_augmented, columns=['RR'])

print(f"\n✅ Data augmentasi selesai. Jumlah data asli: {len(data_scaled)}, total setelah augmentasi: {len(data_augmented)}")

"""# **Model LSTM for RR**"""

def create_lstm_dataset(df, time_step=30):
    X, y = [], []
    for i in range(len(df) - time_step):
        X.append(df[i:(i + time_step), 0])
        y.append(df[i + time_step, 0])
    return np.array(X), np.array(y)

time_step = 30
X, y = create_lstm_dataset(data_augmented.values, time_step)  # GUNAKAN HASIL AUGMENTED
X = X.reshape((X.shape[0], X.shape[1], 1))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

def build_final_model():
    model = Sequential()
    model.add(LSTM(units=96, return_sequences=True, input_shape=(X_train.shape[1], 1)))
    model.add(Dropout(0.1))
    model.add(LSTM(units=64))
    model.add(Dropout(0.4))
    model.add(Dense(1))

    model.compile(optimizer=Adam(learning_rate=0.00681), loss='mean_squared_error')
    return model

model = build_final_model()
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100)

# === Evaluasi Model ===
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

y_train_rescaled = scaler.inverse_transform(y_train.reshape(-1, 1))
y_test_rescaled = scaler.inverse_transform(y_test.reshape(-1, 1))
y_train_pred_rescaled = scaler.inverse_transform(y_train_pred)
y_test_pred_rescaled = scaler.inverse_transform(y_test_pred)

train_mape = mean_absolute_percentage_error(y_train_rescaled, y_train_pred_rescaled)
train_rmse = np.sqrt(mean_squared_error(y_train_rescaled, y_train_pred_rescaled))
train_mae  = mean_absolute_error(y_train_rescaled, y_train_pred_rescaled)

test_mape = mean_absolute_percentage_error(y_test_rescaled, y_test_pred_rescaled)
test_rmse = np.sqrt(mean_squared_error(y_test_rescaled, y_test_pred_rescaled))
test_mae   = mean_absolute_error(y_test_rescaled,  y_test_pred_rescaled)

print("=== Evaluasi Model LSTM (Train-Test Split 80:20) ===")
print(f"Training MAPE : {train_mape * 100:.2f}%")
print(f"Training RMSE : {train_rmse:.2f}")
print(f"Training MAE  : {train_mae:.2f}")
print(f"Testing MAPE  : {test_mape * 100:.2f}%")
print(f"Testing RMSE  : {test_rmse:.2f}")
print(f"Testing  MAE  : {test_mae:.2f}")

#menyusun DataFrame untuk data aktual dan prediksi
result_df = pd.DataFrame({
    'Tanggal': data.index[-len(y_test_rescaled):],
    'Data Aktual RR': y_test_rescaled.flatten(),
    'Prediksi RR': y_test_pred_rescaled.flatten()
})

print("Tabel Perbandingan Prediksi dan Data Aktual RR:")
print(result_df.head(50))

# === Grafik Perbandingan Prediksi dan Aktual (Training) ===
plt.figure(figsize=(12, 5))
plt.plot(y_train_rescaled, label='Aktual Training', color='blue')
plt.plot(y_train_pred_rescaled, label='Prediksi Training', color='orange')
plt.title('Perbandingan Data Aktual dan Prediksi (Training)')
plt.xlabel('Index')
plt.ylabel('RR')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# === Grafik Perbandingan Prediksi dan Aktual (Testing) ===
plt.figure(figsize=(12, 5))
plt.plot(y_test_rescaled, label='Aktual Testing', color='blue')
plt.plot(y_test_pred_rescaled, label='Prediksi Testing', color='red')
plt.title('Perbandingan Data Aktual dan Prediksi (Testing)')
plt.xlabel('Index')
plt.ylabel('RR')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# === Prediksi 7 Hari ke Depan ===
print("\n=== Prediksi RR untuk 7 Hari ke Depan ===")
last_30_days = data_scaled[-30:]
input_seq = last_30_days.reshape(1, 30, 1)
future_predictions = []

for _ in range(7):
    next_pred = model.predict(input_seq)[0][0]
    future_predictions.append(next_pred)
    input_seq = np.append(input_seq[:, 1:, :], [[[next_pred]]], axis=1)

pred_7hari_rescaled = scaler.inverse_transform(np.array(future_predictions).reshape(-1, 1))
last_date = data.index[-1]
future_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=7)
pred_7hari_df = pd.DataFrame({
    'Tanggal': future_dates,
    'Prediksi RR': pred_7hari_rescaled.flatten()
})

print(pred_7hari_df)

# Visualisasi Hasil Prediksi 7 Hari ke Depan
plt.figure(figsize=(10, 5))
plt.plot(pred_7hari_df['Tanggal'], pred_7hari_df['Prediksi RR'], marker='o', color='green')
plt.title('Prediksi RR untuk 7 Hari ke Depan')
plt.xlabel('Tanggal')
plt.ylabel('RR')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# import joblib
# from google.colab import files
# import os

# os.makedirs("model", exist_ok=True)
# # Simpan model dan scaler
# model.save("model/Prediksi RR.h5")
# joblib.dump(scaler, "model/scaler_RR.pkl")
# print("✅ Model & Scaler disimpan.")

# # Unduh otomatis ke perangkat
# files.download("model/Prediksi RR.h5")
# files.download("model/scaler_RR.pkl")

# === K-Fold Cross Validation ===
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error, mean_absolute_error
from sklearn.model_selection import KFold

k = 5
kf = KFold(n_splits=k, shuffle=False)

train_rmse_scores = []
train_mape_scores = []
train_mae_scores = []

test_rmse_scores = []
test_mape_scores = []
test_mae_scores = []

fold = 1

for train_idx, test_idx in kf.split(X):
    X_train_fold, X_test_fold = X[train_idx], X[test_idx]
    y_train_fold, y_test_fold = y[train_idx], y[test_idx]

    # Bangun ulang model di setiap fold
    model = build_final_model()
    model.fit(X_train_fold, y_train_fold, epochs=100, verbose=0)

    # Prediksi
    y_train_pred = model.predict(X_train_fold)
    y_test_pred = model.predict(X_test_fold)

    # Inverse transform
    y_train_rescaled = scaler.inverse_transform(y_train_fold.reshape(-1, 1))
    y_test_rescaled = scaler.inverse_transform(y_test_fold.reshape(-1, 1))
    y_train_pred_rescaled = scaler.inverse_transform(y_train_pred)
    y_test_pred_rescaled = scaler.inverse_transform(y_test_pred)

    # Evaluasi
    train_rmse = np.sqrt(mean_squared_error(y_train_rescaled, y_train_pred_rescaled))
    train_mape = mean_absolute_percentage_error(y_train_rescaled, y_train_pred_rescaled)
    train_mae = mean_absolute_error(y_train_rescaled, y_train_pred_rescaled)

    test_rmse = np.sqrt(mean_squared_error(y_test_rescaled, y_test_pred_rescaled))
    test_mape = mean_absolute_percentage_error(y_test_rescaled, y_test_pred_rescaled)
    test_mae = mean_absolute_error(y_test_rescaled, y_test_pred_rescaled)

    # Simpan hasil
    train_rmse_scores.append(train_rmse)
    train_mape_scores.append(train_mape)
    train_mae_scores.append(train_mae)

    test_rmse_scores.append(test_rmse)
    test_mape_scores.append(test_mape)
    test_mae_scores.append(test_mae)

    print(f"\nFold {fold}:")
    print(f"Training MAPE : {train_mape * 100:.2f}%")
    print(f"Training MAE  : {train_mae:.2f}")
    print(f"Training RMSE : {train_rmse:.2f}")
    print(f"Testing MAPE  : {test_mape * 100:.2f}%")
    print(f"Testing MAE   : {test_mae:.2f}")
    print(f"Testing RMSE  : {test_rmse:.2f}")
    fold += 1

# === Rata-Rata Hasil Evaluasi ===
print("\n=== Rata-Rata Hasil Evaluasi LSTM dengan 5-Fold Cross Validation ===")
print(f"Training MAPE : {np.mean(train_mape_scores) * 100:.2f}%")
print(f"Training MAE  : {np.mean(train_mae_scores):.2f}")
print(f"Training RMSE : {np.mean(train_rmse_scores):.2f}")
print(f"Testing MAPE  : {np.mean(test_mape_scores) * 100:.2f}%")
print(f"Testing MAE   : {np.mean(test_mae_scores):.2f}")
print(f"Testing RMSE  : {np.mean(test_rmse_scores):.2f}")

# Buat list fold 1-5
folds = list(range(1, k + 1))

# === Grafik RMSE per Fold ===
plt.figure(figsize=(10, 5))
plt.plot(folds, train_rmse_scores, marker='o', label='Training RMSE')
plt.plot(folds, test_rmse_scores, marker='s', label='Testing RMSE')
plt.title('RMSE per Fold')
plt.xlabel('Fold')
plt.ylabel('RMSE')
plt.xticks(folds)
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# === Grafik MAPE per Fold ===
plt.figure(figsize=(10, 5))
plt.plot(folds, [x * 100 for x in train_mape_scores], marker='o', label='Training MAPE')
plt.plot(folds, [x * 100 for x in test_mape_scores], marker='s', label='Testing MAPE')
plt.title('MAPE per Fold')
plt.xlabel('Fold')
plt.ylabel('MAPE (%)')
plt.xticks(folds)
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# === Grafik MAE per Fold ===
plt.figure(figsize=(10, 5))
plt.plot(folds, train_mae_scores, marker='o', label='Training MAE')
plt.plot(folds, test_mae_scores, marker='s', label='Testing MAE')
plt.title('MAE per Fold')
plt.xlabel('Fold')
plt.ylabel('MAE')
plt.xticks(folds)
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()