# -*- coding: utf-8 -*-
"""prediksi_tavg_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-z48MvVNSTZXfz7UrNul_x3DYneMpXV
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error, mean_absolute_error
from sklearn.model_selection import KFold

from google.colab import drive
drive.mount('/content/drive')

preprocessed_file_path = '/content/drive/MyDrive/Colab Notebooks/DATA CUACA HARIAN BMKG (1 JANUARI 2022 - 31 DESEMBER 2024)_preprocessing result.csv'

data = pd.read_csv(preprocessed_file_path, parse_dates=['Tanggal'], index_col='Tanggal')

# Cek statistik dasar temperatur udara
print("RR min     :", data['RR'].min())
print("RR max     :", data['RR'].max())
print("RR median  :", data['RR'].median())
print("RR mean    :", data['RR'].mean())
print("Tavg std dev :", data['Tavg'].std())
print("RR non-zero count:", (data['RR'] > 0).sum())

"""# **Normalisasi**"""

plt.figure(figsize=(8, 5))
plt.hist(data['Tavg'], bins=50)
plt.title("Distribusi Curah Hujan (Tavg) Sebelum MinMax Scaler")
plt.xlabel("Tavg (setelah scaling)")
plt.ylabel("Frekuensi")
plt.grid(True)
plt.tight_layout()
plt.show()

#ambil data Tavg asli
tavg_asli = data[['Tavg']].copy()

#menerapkan Moving Average 7 hari
tavg_smooth = tavg_asli.rolling(window=7, center=True, min_periods=1).mean()
print(tavg_smooth[-30:].values)

scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(tavg_smooth[['Tavg']])
scaled_data = pd.DataFrame(data_scaled, columns=['tavg_smooth'], index=data.index)

plt.figure(figsize=(8, 5))
plt.hist(data_scaled, bins=50)
plt.title("Distribusi Curah Hujan (Tavg) Setelah MinMaxScaler")
plt.xlabel("Tavg (setelah scaling)")
plt.ylabel("Frekuensi")
plt.grid(True)
plt.tight_layout()
plt.show()

"""# **Model LSTM for Tavg**"""

# Membuat dataset untuk LSTM
def create_lstm_dataset(df, time_step=30):
    X, y = [], []
    for i in range(len(df) - time_step):
        X.append(df[i:(i + time_step), 0])
        y.append(df[i + time_step, 0])
    return np.array(X), np.array(y)

# Membuat dataset
time_step = 30
X, y = create_lstm_dataset(data_scaled, time_step)
X = X.reshape((X.shape[0], X.shape[1], 1))

# Split Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# Model LSTM
def build_final_model():
    model = Sequential()
    model.add(LSTM(50, return_sequences=True, input_shape=(X.shape[1], X.shape[2])))
    model.add(LSTM(50))
    model.add(Dense(1))
    model.compile(optimizer=Adam(learning_rate=0.01), loss='mean_squared_error')
    return model

model = build_final_model()
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=50, batch_size=72, verbose=1)

# === Evaluasi Model ===
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

y_train_rescaled = scaler.inverse_transform(y_train.reshape(-1, 1))
y_test_rescaled = scaler.inverse_transform(y_test.reshape(-1, 1))
y_train_pred_rescaled = scaler.inverse_transform(y_train_pred)
y_test_pred_rescaled = scaler.inverse_transform(y_test_pred)

train_mape = mean_absolute_percentage_error(y_train_rescaled, y_train_pred_rescaled)
train_rmse = np.sqrt(mean_squared_error(y_train_rescaled, y_train_pred_rescaled))

test_mape = mean_absolute_percentage_error(y_test_rescaled, y_test_pred_rescaled)
test_rmse = np.sqrt(mean_squared_error(y_test_rescaled, y_test_pred_rescaled))

std_test_tavg = np.std(y_test_rescaled)

print("=== Evaluasi Model LSTM (Train-Test Split 80:20) ===")
print()
print(f"Training MAPE : {train_mape * 100:.2f}%")
print(f"Testing MAPE  : {test_mape * 100:.2f}%")

print()
# Evaluasi RMSE
print(f"Training RMSE         : {train_rmse:.2f}")
print(f"Testing RMSE          : {test_rmse:.2f}")
print(f"Std Dev RR (Test Set) : {std_test_tavg:.2f}")
print(f"RMSE < Std Dev?       : {'✅ Baik' if test_rmse < std_test_tavg else '❌ Kurang Baik'}")
print()

#menyusun DataFrame untuk data aktual dan prediksi
result_df = pd.DataFrame({
    'Tanggal': data.index[-len(y_test_rescaled):],
    'Data Aktual Tavg': y_test_rescaled.flatten(),
    'Prediksi Tavg': y_test_pred_rescaled.flatten()
})

print("Tabel Perbandingan Prediksi dan Data Aktual Tavg:")
print(result_df.head(50))

# === Grafik Perbandingan Prediksi dan Aktual (Training) ===
plt.figure(figsize=(12, 5))
plt.plot(y_train_rescaled, label='Aktual Training', color='blue')
plt.plot(y_train_pred_rescaled, label='Prediksi Training', color='orange')
plt.title('Perbandingan Data Aktual dan Prediksi (Training)')
plt.xlabel('Index')
plt.ylabel('Tavg')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# === Grafik Perbandingan Prediksi dan Aktual (Testing) ===
plt.figure(figsize=(12, 5))
plt.plot(y_test_rescaled, label='Aktual Testing', color='blue')
plt.plot(y_test_pred_rescaled, label='Prediksi Testing', color='red')
plt.title('Perbandingan Data Aktual dan Prediksi (Testing)')
plt.xlabel('Index')
plt.ylabel('Tavg')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# === Prediksi 7 Hari ke Depan ===
print("\n=== Prediksi Tavg untuk 7 Hari ke Depan ===")
last_30_days = data_scaled[-30:]
input_seq = last_30_days.reshape(1, 30, 1)
future_predictions = []

for _ in range(7):
    next_pred = model.predict(input_seq)[0][0]
    future_predictions.append(next_pred)
    input_seq = np.append(input_seq[:, 1:, :], [[[next_pred]]], axis=1)

pred_7hari_rescaled = scaler.inverse_transform(np.array(future_predictions).reshape(-1, 1))
last_date = data.index[-1]
future_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=7)
pred_7hari_df = pd.DataFrame({
    'Tanggal': future_dates,
    'Prediksi Tavg': pred_7hari_rescaled.flatten()
})

print(pred_7hari_df)

# Visualisasi Hasil Prediksi 7 Hari ke Depan
plt.figure(figsize=(10, 5))
plt.plot(pred_7hari_df['Tanggal'], pred_7hari_df['Prediksi Tavg'], marker='o', color='green')
plt.title('Prediksi Tavg untuk 7 Hari ke Depan')
plt.xlabel('Tanggal')
plt.ylabel('Tavg')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# import joblib
# from google.colab import files
# import os

# os.makedirs("model", exist_ok=True)

# # Simpan model dan scaler
# model.save("model/tavg_model.h5")
# joblib.dump(scaler, "model/scaler_tavg.pkl")

# print("✅ Model & Scaler disimpan.")

# # Unduh otomatis ke perangkat
# files.download("model/tavg_model.h5")
# files.download("model/scaler_tavg.pkl")